<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\**\*.*" />
  </ItemGroup>

  <Import Project="../AmongUs.props" />

</Project>
