<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Description>TOUM Vessel</Description>
    <RootNamespace>VesselRoleMod</RootNamespace>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <Version>$(VersionPrefix)-$(VersionSuffix)</Version>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\**\*.*" />
  </ItemGroup>

  <Import Project="../AmongUs.props" />

  <ItemGroup>
    <EditorConfigFiles Remove="C:\Users\David Higueros\Documents\.Personal Projects\AmongDiscord\VesselRoleMod\VesselRoleMod\.editorconfig" />
  </ItemGroup>

  <ItemGroup>
    <None Include="C:\Users\David Higueros\Documents\.Personal Projects\AmongDiscord\VesselRoleMod\VesselRoleMod\.editorconfig" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Update="AllOfUs.MiraAPI" Version="0.4.1" />
    <PackageReference Update="AmongUs.GameLibs.Steam" Version="2026.3.31" />
  </ItemGroup>

</Project>
