<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Description>TOUM Vessel</Description>
    <RootNamespace>VesselRoleMod</RootNamespace>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <Version>$(VersionPrefix)-$(VersionSuffix)</Version>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\**\*.*" />
  </ItemGroup>

  <Import Project="../AmongUs.props" />

</Project>
